apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
  labels:
    app: myapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      name: myapp1
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1-container
        image: mamathasama/myapp1:latest
        ports:
        - containerPort: 8080

