apiVersion: v1
kind: Service
metadata:
  name: myapp1-service
  labels:
    app: myapp1
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32100
  selector:
    app: myapp1

      
